# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chuan Wang's Website
author :
  name : Chuan Wang
  email: wangchuan2400@gmail.com
  github : wangchuan
  linkedin: wangchuan2400
description: > # this means to ignore newlines until "baseurl:"
  This is an example
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  wangchuan

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

menuitems:
    - { title:    Projects,
        url:      /projects.html }
    - { title:    Publications,
        url:      /publications.html }
    - { title:    Curriculum Vitae,
        url:      /cv.html}
    - { title:    Notes,
        dropdown: true,
        subitems: [ { title: Recent Notes,
                      url: /archive/index.html   },
                    { title: Coding,
                      category: coding,
                      url:   /coding.html },
                    { title: Research,
                      category: research,
                      url:   /research.html },
                    { title: Tags,
                      url:   /tags.html }]}
# support the pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/archive/page:num"

JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex:
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  #atom_path : /feed.atom
  #rss_path : /feed.rss

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  
  analytics :
    provider : google
    google :
        tracking_id : 'UA-44085641-1'
    # getclicky :
    #   site_id :
    # mixpanel :
    #     token : '_MIXPANEL_TOKEN_'
    # piwik :
    #     baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
    #     idsite : '1'                   # the id of the site on Piwik


  # Settings for sharing
  # Sharing is for things like google plus, facebook, twitter, linkedin, etc.
  # Add a google plus one button 	  => provider : googleplus
  # Add a facebook like button        => provider : facebook
  # Add a twitter button              => provider : twitter
  # Add a linkedin button             => provider : linkedin
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  # Set 'provider' to an array of sharing providers if you want to use more than one
  # Set the post's 'sharing' metadata to 'false' to turn sharing off for the page
  #
  # NOTE: in order to make the buttons aligned in the same line, it's better to
  # put the 'facebook' at the frist and put the 'googleplus' at the last.
  #
  sharing :
     provider : [facebook, googleplus]
     facebook :
       layout : button_count
       faces : false
       width : 90
     googleplus :
       annotation : bubble
       size : medium
       width : 20
     twitter :
       size :
       via :
       count :
     linkedin :
       counter : right

  # Settings for all other include helpers can be defined by creating
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

